version: '3'

services:
  nginx:
    logging:
      driver: gcplogs
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    logging:
      driver: gcplogs
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  trillo-data-service:
    logging:
      driver: gcplogs
    image: gcr.io/project-trillort/trillo-rt/trillo-data-service:3.0.296
    restart: unless-stopped
    environment:
      DEFAULT_DATA_SERVER_HOST: __sql_server__
      DEFAULT_DATA_SERVER_USERNAME: root
      DEFAULT_DATA_SERVER_PASSWORD: __db_secret__
      REPO_DIR: /trillo-repo
      CREDENTIALS_PROVIDER: CRYPTO_SHA512
    volumes:
      - ./rt-repo:/trillo-repo

  trillo-pubsub:
    logging:
      driver: gcplogs
    image: gcr.io/project-trillort/trillo-gke-tasker:3.0.273
    restart: unless-stopped
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/google/key.json
      CONFIG_JSON: /var/pubsub/config.json
    volumes:
      - ./secrets:/var/secrets:ro
      - ./pubsub:/var/pubsub:ro

  trillo-rt:
    logging:
      driver: gcplogs
    image: gcr.io/project-trillort/trillo-rt:3.0.296
    restart: unless-stopped
    ports:
      - 8020:8020
    environment:
      DATA_SERVICE_URL: 'https://trillo-data-service:8030'
      TRILLO_PACKAGED_ORG_NAME: cloud
      CREDENTIALS_PROVIDER: CRYPTO_SHA512
      GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/google/key.json
      GCP_BUCKET_NAME: __gcp_bucket_name__
      GCP_SERVICE_NAME: _default_
      GCS_FILE_SERVER: __gcs_file_server__
      GCS_FILE_SERVER_USER: root
      RSA_PRIVATE_KEY: /var/secrets/ssh/trillo-ssh
      DEFAULT_DATA_SERVER_HOST: __sql_server__
      DEFAULT_DATA_SERVER_USERNAME: root
      DEFAULT_DATA_SERVER_PASSWORD: __db_secret__
      QUARTZ_ENABLED: 'true'
      MAIL_REFERENCE_SERVER: https://__server_fqdn_name__
      REPO_DIR: /trillo-repo
      APPDATA_DIR: /trillo-rt-appdata
      TRILLO_USE_REDIS: 'false'
    volumes:
      - ./rt-repo:/trillo-repo
      - ./rt-appdata:/trillo-rt-appdata
      - ./secrets:/var/secrets:ro
    depends_on:
      - trillo-data-service
